/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings src/worker-configuration.d.ts` (hash: 19d1863153a001499c093448205ac0ff)
interface __BaseEnv_CloudflareBindings {
  KV: KVNamespace
  ICONS: R2Bucket
  DB: D1Database
  ASSETS: Fetcher
  AUTH_MODE: 'builtin' | 'development'
  APP_VERSION: '0.1.0'
  SESSION_COOKIE_NAME?: 'dockmark_session'
  SESSION_TTL_SECONDS?: '604800'
  PASSWORD_PBKDF2_ITERATIONS?: '100000'
  SETUP_TOKEN: string
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./index')
  }
  interface ProductionEnv {
    KV: KVNamespace
    ICONS: R2Bucket
    DB: D1Database
    ASSETS: Fetcher
    AUTH_MODE: 'builtin'
    APP_VERSION: '0.1.0'
    SESSION_COOKIE_NAME: 'dockmark_session'
    SESSION_TTL_SECONDS: '604800'
    PASSWORD_PBKDF2_ITERATIONS: '100000'
    SETUP_TOKEN: string
  }
  interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
