/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/worker-configuration.d.ts --env-interface CloudflareBindings --include-runtime false` (hash: 4a7b880a794d4bcead2f1b4b40de145f)
interface __BaseEnv_CloudflareBindings {
	KV: KVNamespace;
	DB: D1Database;
	ASSETS: Fetcher;
	AUTH_MODE: "builtin" | "development";
	APP_VERSION: "0.1.0";
	SESSION_COOKIE_NAME?: "dockmark_session";
	SESSION_TTL_SECONDS?: "604800";
	PASSWORD_PBKDF2_ITERATIONS?: "310000";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface ProductionEnv {
		KV: KVNamespace;
		DB: D1Database;
		ASSETS: Fetcher;
		AUTH_MODE: "builtin";
		APP_VERSION: "0.1.0";
		SESSION_COOKIE_NAME: "dockmark_session";
		SESSION_TTL_SECONDS: "604800";
		PASSWORD_PBKDF2_ITERATIONS: "310000";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
