/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/worker-configuration.d.ts --env-interface CloudflareBindings --include-runtime false` (hash: 008156c58780ed601a94fff96f9e752e)
interface __BaseEnv_CloudflareBindings {
	KV: KVNamespace;
	DB: D1Database;
	ASSETS: Fetcher;
	AUTH_MODE: "builtin" | "development";
	APP_VERSION: "0.1.0";
	SESSION_COOKIE_NAME?: "dockmark_session";
	SESSION_TTL_SECONDS?: "604800";
	PASSWORD_PBKDF2_ITERATIONS?: "100000";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface ProductionEnv {
		KV: KVNamespace;
		DB: D1Database;
		ASSETS: Fetcher;
		AUTH_MODE: "builtin";
		APP_VERSION: "0.1.0";
		SESSION_COOKIE_NAME: "dockmark_session";
		SESSION_TTL_SECONDS: "604800";
		PASSWORD_PBKDF2_ITERATIONS: "100000";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
